name: Workflow of exercise 3

# Events triggering the workflow
on: [push]

env:
    fruit: "banana"

# Group of jobs to run as part of the workflow
jobs:
  fruit-seller:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I love $fruit"