name: Workflow of exercise 3

# Events triggering the workflow
on: [push]

env:
    fruit: "banana"

# Group of jobs to run as part of the workflow
jobs:
  fruit-seller:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I love ${{ env.fruit }}"
      - run: echo "My github token is ${{ secrets.GITHUB_TOKEN }}"
      - if: ${{ env.fruit == 'banana' }}
        run: echo "Fruit is $fruit"
